### ISSUE TITLE
UTF-8 인코딩

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/activity1-Hwi-gyeom#1]
소스에서 한글을 사용하는데, 인코딩이 적절하지 않아 잘 보이지 않습니다. 수정 바랍니다.

**Comment by Hwi-gyeom** [comment]
아, 지금봤네요... 최종버전에는 주석 말고는 한글이 없는데 혹시 아직도 작동이 원활하지않다면 말씀해주시면 수정하도록하겠습니다.

**Comment by dinggul** [comment]
아 아닙니다 ㅋㅋ 채점에는 별 문제가 없습니다.
다만 utf-8을 캐릭터 인코딩으로 많이 사용하고 있기 때문에, 이점을 지켜서 코드등을 작성하면
그 코드를 리뷰하는 사람이나 협업하는 사람이 불편을 겪지 않을 수 있다는 comment를 드린 것입니다.

추측하기로 윈도우즈 환경에서 코드를 작성하신 것 같은데, 윈도우즈 환경은 한글 기본 인코딩으로 euc-kr이나 cp949를 사용하는 경우가 많기 때문에 이 점을 확인해두면 좋습니다.
